[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pygal-stubs"
version = "3.1.3.1"
requires-python = ">= 3.10"
authors = [
    { name = "Manuel Corsunsky Gayá", email = "manuelcorsunsky@gmail.com" },
]
maintainers = [
    { name = "Manuel Corsunsky Gayá", email = "manuelcorsunsky@gmail.com" },
]
description = "Type stubs for pygal"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Typing :: Stubs Only",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = ["types-lxml"]

[project.urls]
Repository = "https://github.com/manucorsu/pygal-stubs"
Issues = "https://github.com/manucorsu/pygal-stubs/issues"

[project.optional-dependencies]
dev = ["hatch", "black", "ruff", "basedpyright", "pygal", "lxml"]

[tool.hatch.build.targets.wheel]
packages = ["pygal-stubs"]

[tool.black]
target-version = ["py310"]
line-length = 88
include = ".pyi$"
exclude = '/(\.git|\.venv|\.mypy_cache|\.ruff_cache|\.pytest_cache)/'

[tool.ruff.lint.per-file-ignores]
"**/*.pyi" = ["A001", "A002", "N801"]
# In order:
# "Variable is shadowing a Python builtin",
# "Function argument is shadowing a Python builtin",
# "Class name should use CapWords convention"

[tool.hatch.envs.hatch-check-code]
features = ["dev"]

[tool.hatch.envs.hatch-check-code.scripts]
lint-check = "ruff check {args:.}"
lint-fix = "ruff check --fix {args:.}"


[tool.hatch.envs.hatch-check-fmt]
features = ["dev"]

[tool.hatch.envs.hatch-check-fmt.scripts]
format-check = "black --check --diff {args:.}"
format-fix = "black {args:.}"


[tool.hatch.envs.hatch-check-types]
features = ["dev"]

[tool.hatch.envs.hatch-check-types.scripts]
check = "basedpyright {args:.}"
check-summarize = "basedpyright {args:.}"
