[build-system]
requires = ["uv_build>=0.12.23,<0.13"]
build-backend = "uv_build"


[project]
name = "pygal-stubs"
version = "3.1.3.4"
requires-python = ">= 3.11"
authors = [
    { name = "Manuel Corsunsky Gayá", email = "manuelcorsunsky@gmail.com" },
]
maintainers = [
    { name = "Manuel Corsunsky Gayá", email = "manuelcorsunsky@gmail.com" },
]
description = "Type stubs for pygal"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Typing :: Stubs Only",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Scientific/Engineering :: Visualization",
    "Typing :: Stubs Only",
]
dependencies = ["typing-extensions", "types-lxml", "django-types"]

[project.scripts]
check = "_check:main"

[project.urls]
Repository = "https://github.com/manucorsu/pygal-stubs"
Issues = "https://github.com/manucorsu/pygal-stubs/issues"

[dependency-groups]
dev = [
    "ruff",
    "basedpyright",
    "mypy",
    "pygal",
    "lxml",
    "pyquery",
    "Flask",
    "Django",
    "CairoSVG",
]

[tool.uv.build-backend]
module-name = "pygal-stubs"
module-root = ""

[tool.ruff]
target-version = "py311"

[tool.ruff.lint.per-file-ignores]
"**/*.pyi" = ["A001", "A002", "N801"]
# In order:
# "Variable is shadowing a Python builtin",
# "Function argument is shadowing a Python builtin",
# "Class name should use CapWords convention"

[tool.basedpyright]
pythonVersion = "3.11"
reportUnsafeMultipleInheritance = false
reportUnusedCallResult = false
