from pygal._compat import is_list_like as is_list_like
from pygal.graph.base import BaseGraph as BaseGraph

class PublicApi(BaseGraph):
    def add(self, title, values, **kwargs): ...
    def __call__(self, *args, **kwargs): ...
    def add_xml_filter(self, callback): ...
    def render(self, is_unicode: bool = False, **kwargs): ...
    def render_tree(self, **kwargs): ...
    def render_table(self, **kwargs): ...
    def render_pyquery(self, **kwargs): ...
    def render_in_browser(self, **kwargs) -> None: ...
    def render_response(self, **kwargs): ...
    def render_django_response(self, **kwargs): ...
    def render_data_uri(self, **kwargs): ...
    def render_to_file(self, filename, **kwargs) -> None: ...
    def render_to_png(self, filename=None, dpi: int = 72, **kwargs): ...
    def render_sparktext(self, relative_to=None): ...
    def render_sparkline(self, **kwargs): ...
