from typing import TypeVar, overload

from pygal._compat import timestamp as timestamp
from pygal.adapters import positive as positive
from pygal.graph.xy import XY as XY
from datetime import datetime, time, timedelta

_T = TypeVar("_T")

@overload
def datetime_to_timestamp(x: datetime) -> float: ...
@overload
def datetime_to_timestamp(
    x: _T,
) -> _T: ...  # if x isn't a datetime it gets returned without modification
@overload
def datetime_to_time(x: datetime) -> time: ...
@overload
def datetime_to_time(x: _T) -> _T: ...
@overload
def time_to_datetime(x: time) -> datetime: ...
@overload
def time_to_datetime(x: _T) -> _T: ...
@overload
def timedelta_to_seconds(x: timedelta) -> float: ...
@overload
def timedelta_to_seconds(x: _T) -> _T: ...
@overload
def time_to_seconds(x: time) -> float: ...
@overload
def time_to_seconds(x: str) -> str: ...
@overload
def time_to_seconds(x: float) -> float: ...
def seconds_to_time(x: float) -> time: ...

class DateTimeLine(XY): ...
class DateLine(DateTimeLine): ...
class TimeLine(DateTimeLine): ...
class TimeDeltaLine(XY): ...
