from pygal._compat import timestamp as timestamp
from pygal.adapters import positive as positive
from pygal.graph.xy import XY as XY

def datetime_to_timestamp(x): ...
def datetime_to_time(x): ...
def date_to_datetime(x): ...
def time_to_datetime(x): ...
def timedelta_to_seconds(x): ...
def time_to_seconds(x): ...
def seconds_to_time(x): ...

class DateTimeLine(XY): ...
class DateLine(DateTimeLine): ...
class TimeLine(DateTimeLine): ...
class TimeDeltaLine(XY): ...
