from decimal import Decimal
from typing import Literal, TypeVar, overload

from _typeshed import SupportsDunderLT

_T = TypeVar("_T")
_ComparableT = TypeVar("_ComparableT", bound=SupportsDunderLT[int])

@overload
def positive(x: None) -> None: ...
@overload
def positive(x: str) -> str: ...
@overload
def positive(x: _ComparableT) -> _ComparableT | int: ...
@overload
def not_zero(x: Literal[0, False]) -> None: ...
@overload
def not_zero(x: float | None) -> float | None: ...
@overload
def not_zero(x: _T) -> _T: ...
@overload
def none_to_zero(x: None) -> Literal[0]: ...
@overload
def none_to_zero(x: _T) -> _T: ...
@overload
def decimal_to_float(x: Decimal) -> float: ...
@overload
def decimal_to_float(x: _T) -> _T: ...
