def normalize_float(f): ...
def rgb_to_hsl(r, g, b): ...
def hsl_to_rgb(h, s, l): ...
def parse_color(color): ...
def unparse_color(r, g, b, a, type): ...
def is_foreground_light(color): ...
def adjust(color, attribute, percent): ...
def rotate(color, percent): ...
def saturate(color, percent): ...
def desaturate(color, percent): ...
def lighten(color, percent): ...
def darken(color, percent): ...
