from typing import Literal, TypeAlias, overload

_ColorFormat: TypeAlias = Literal[
    "#rgb", "#rgba", "#rrggbb", "#rrggbbaa", "rgb", "rgba"
]

def normalize_float(f: float) -> float | int: ...
def rgb_to_hsl(
    r: float | None, g: float | None, b: float | None
) -> tuple[float | int, float | int, float | int]: ...
def hsl_to_rgb(h: float, s: float, l: float) -> tuple[int, int, int]: ...
def parse_color(
    color: str,
) -> (
    tuple[int, int, int, int | float, _ColorFormat]
    | tuple[None, None, None, None, None]
): ...
@overload
def unparse_color(
    r: int, g: int, b: int, a: object, type: Literal["#rgb", "#rrggbb"]
) -> str: ...
@overload
def unparse_color(
    r: int, g: int, b: int, a: float, type: Literal["#rgba", "#rrggbbaa"]
) -> str: ...
@overload
def unparse_color(
    r: float, g: float, b: float, a: object, type: Literal["rgb"]
) -> str: ...
@overload
def unparse_color(
    r: float, g: float, b: float, a: float, type: Literal["rgba"]
) -> str: ...
@overload
def unparse_color(
    r: object, g: object, b: object, a: object, type: object
) -> str | None: ...
def is_foreground_light(color: str) -> bool: ...
def adjust(color: str, attribute: int, percent: float) -> str | None: ...
def rotate(color: str, percent: float) -> str | None: ...
def saturate(color: str, percent: float) -> str | None: ...
def desaturate(color: str, percent: float) -> str | None: ...
def lighten(color: str, percent: float) -> str | None: ...
def darken(color: str, percent: float) -> str | None: ...
