from _typeshed import Incomplete

class Etree:
    lxml: Incomplete
    def __init__(self) -> None: ...
    def __getattribute__(self, attr): ...
    def to_lxml(self) -> None: ...
    def to_etree(self) -> None: ...

etree: Incomplete
