def erfinv(x, a: float = 0.147): ...
def norm_ppf(x): ...
def ppf(x, n): ...
def confidence_interval_continuous(point_estimate, stddev, sample_size, confidence: float = 0.95, **kwargs): ...
def confidence_interval_dichotomous(point_estimate, sample_size, confidence: float = 0.95, bias: bool = False, percentage: bool = True, **kwargs): ...
def confidence_interval_manual(point_estimate, low, high): ...
