from _typeshed import Incomplete
from collections.abc import Generator, Iterable, Sequence
from re import Pattern
from typing import Callable, Generic, ParamSpec, SupportsInt, TypeVar

from pygal.svg import Svg
from xml.etree.ElementTree import Element as _StdEtreeElement
from lxml.etree import (
    Element as _LxmlElement,
)

_T = TypeVar("_T")
_R = TypeVar("_R")

def float_format(number: float) -> str: ...
def majorize(values: Sequence[float]) -> list[float]: ...
def round_to_int(number: float, precision: SupportsInt) -> float: ...
def round_to_float(number: float, precision: float) -> float: ...
def round_to_scale(number: float, precision: float) -> float: ...
def cut(list_: list[_T], index: int | str = 0) -> list[_T]: ...
def rad(degrees: float) -> float: ...
def deg(radiants: float) -> float: ...
def template(string: str, **kwargs: object) -> str: ...
def swap(tuple_: tuple[_T, ...]) -> tuple[_T, ...]: ...
def ident(x: _T) -> _T: ...
def compute_logarithmic_scale(
    min_: float, max_: float, min_scale: float, max_scale: float
) -> list[float]: ...
def compute_scale(
    min_: float,
    max_: float,
    logarithmic: bool,
    order_min: int | None,
    min_scale: float,
    max_scale: float,
) -> list[float]: ...
def text_len(length: int, fs: int) -> float: ...
def reverse_text_len(width: float, fs: int) -> int: ...
def get_text_box(text: str, fs: int) -> tuple[int, float]: ...
def get_texts_box(texts: Sequence[str], fs: int) -> tuple[int, float]: ...
def decorate(
    svg: Svg, node: _StdEtreeElement | _LxmlElement, metadata: dict[str, object]
) -> _StdEtreeElement | _LxmlElement: ...
def alter(
    node: _StdEtreeElement | _LxmlElement, metadata: dict[str, object]
) -> None: ...
def truncate(string: str, index: int) -> str: ...

class cached_property(Generic[_T, _R]):
    def __init__(
        self,
        getter: Callable[[_T], _R],
        doc: str | None = None,
    ) -> None: ...
    def __get__(
        self,
        obj: _T | None,
        type_: _T | None,
    ) -> _R | "cached_property[_T, _R]": ...

css_comments: Pattern[str]

def minify_css(css: str) -> str: ...

_P = ParamSpec("_P")
_B = TypeVar("_B")
_C = TypeVar("_C")

def compose(f: Callable[[_B], _C], g: Callable[_P, _B]) -> Callable[_P, _C]: ...
def safe_enumerate(iterable: Iterable[_T]) -> Generator[tuple[int, _T], None, None]: ...
def split_title(title, width, title_fs): ...
def filter_kwargs(fun, kwargs): ...
def coord_project(rho, alpha): ...
def coord_diff(x, y): ...
def coord_format(x): ...
def coord_dual(r): ...
def coord_abs_project(center, rho, theta): ...
def mergextend(list1, list2): ...
def merge(dict1, dict2) -> None: ...
