from collections.abc import Callable, Generator, Hashable, Iterable, Mapping, Sequence
from re import Pattern
from typing import (
    Generic,
    ParamSpec,
    SupportsInt,
    TypeVar,
    overload,
)
from xml.etree.ElementTree import Element as _StdEtreeElement

from lxml.etree import Element as _LxmlElement
from pygal.svg import Svg

_T = TypeVar("_T")
_R = TypeVar("_R")

def float_format(number: float) -> str: ...
def majorize(values: Sequence[float]) -> list[float]: ...
def round_to_int(number: float, precision: SupportsInt) -> float: ...
def round_to_float(number: float, precision: float) -> float: ...
def round_to_scale(number: float, precision: float) -> float: ...
def cut(list_: list[_T], index: int | str = 0) -> list[_T]: ...
def rad(degrees: float) -> float: ...
def deg(radiants: float) -> float: ...
def template(string: str, **kwargs: object) -> str: ...
def swap(tuple_: tuple[_T, ...]) -> tuple[_T, ...]: ...
def ident(x: _T) -> _T: ...
def compute_logarithmic_scale(
    min_: float, max_: float, min_scale: float, max_scale: float
) -> list[float]: ...
def compute_scale(
    min_: float,
    max_: float,
    logarithmic: bool,
    order_min: int | None,
    min_scale: float,
    max_scale: float,
) -> list[float]: ...
def text_len(length: int, fs: int) -> float: ...
def reverse_text_len(width: float, fs: int) -> int: ...
def get_text_box(text: str, fs: int) -> tuple[int, float]: ...
def get_texts_box(texts: Sequence[str], fs: int) -> tuple[int, float]: ...
def decorate(
    svg: Svg, node: _StdEtreeElement | _LxmlElement, metadata: dict[str, object]
) -> _StdEtreeElement | _LxmlElement: ...
def alter(
    node: _StdEtreeElement | _LxmlElement, metadata: dict[str, object]
) -> None: ...
def truncate(string: str, index: int) -> str: ...

class cached_property(Generic[_T, _R]):
    def __init__(
        self,
        getter: Callable[[_T], _R],
        doc: str | None = None,
    ) -> None: ...
    def __get__(
        self,
        obj: _T | None,
        type_: _T | None,
    ) -> _R | cached_property[_T, _R]: ...

css_comments: Pattern[str]

def minify_css(css: str) -> str: ...

_P = ParamSpec("_P")
_B = TypeVar("_B")
_C = TypeVar("_C")

def compose(f: Callable[[_B], _C], g: Callable[_P, _B]) -> Callable[_P, _C]: ...
def safe_enumerate(iterable: Iterable[_T]) -> Generator[tuple[int, _T], None, None]: ...
def split_title(
    title: str, width: float, title_fs: int
) -> Generator[str, None, None]: ...
def filter_kwargs(
    fun: Callable[..., object],
    kwargs: Mapping[str, object],
) -> dict[str, object]: ...
def coord_project(rho: float, alpha: float) -> tuple[float, float]: ...
def coord_diff(x: float, y: float) -> tuple[float, float]: ...
def coord_format(x: float) -> str: ...
def coord_dual(r: float) -> float: ...
def coord_abs_project(
    center: float, rho: float, theta: float
) -> tuple[float, float]: ...

_T2 = TypeVar("_T2")

@overload
def mergextend(list1: None, list2: object) -> None: ...
@overload
def mergextend(list1: Sequence[_T], list2: Sequence[_T2]) -> list[_T | _T2]: ...
def merge(
    dict1: Mapping[Hashable, object], dict2: Mapping[Hashable, object]
) -> None: ...
