from _typeshed import Incomplete
from collections.abc import Generator, Sequence
from typing import SupportsInt, TypeVar

_T = TypeVar("_T")

def float_format(number: float) -> str: ...
def majorize(values: Sequence[float]) -> list[float]: ...
def round_to_int(number: float, precision: SupportsInt) -> float: ...
def round_to_float(number: float, precision: float) -> float: ...
def round_to_scale(number: float, precision: float) -> float: ...

def cut(list_: list[_T], index: int | str = 0) -> list[_T]: ...
def rad(degrees: float) -> float: ...
def deg(radiants: float) -> float: ...
def template(string:str, **kwargs: object) -> str: ...

def swap(tuple_: tuple[_T, ...]) -> tuple[_T, ...]: ...
def ident(x: _T) -> _T: ...

def compute_logarithmic_scale(min_, max_, min_scale, max_scale): ...
def compute_scale(min_, max_, logarithmic, order_min, min_scale, max_scale): ...
def text_len(length, fs): ...
def reverse_text_len(width, fs): ...
def get_text_box(text, fs): ...
def get_texts_box(texts, fs): ...
def decorate(svg, node, metadata): ...
def alter(node, metadata) -> None: ...
def truncate(string, index): ...

class cached_property:
    getter: Incomplete
    __module__: Incomplete
    __doc__: Incomplete
    def __init__(self, getter, doc=None) -> None: ...
    def __get__(self, obj, type_=None): ...

css_comments: Incomplete

def minify_css(css): ...
def compose(f, g): ...
def safe_enumerate(iterable) -> Generator[Incomplete]: ...
def split_title(title, width, title_fs): ...
def filter_kwargs(fun, kwargs): ...
def coord_project(rho, alpha): ...
def coord_diff(x, y): ...
def coord_format(x): ...
def coord_dual(r): ...
def coord_abs_project(center, rho, theta): ...
def mergextend(list1, list2): ...
def merge(dict1, dict2) -> None: ...
