from typing import Literal, TypeAlias, overload

class Margin:
    top: float
    right: float
    bottom: float
    left: float
    def __init__(
        self, top: float, right: float, bottom: float, left: float
    ) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...

class Box:
    margin: float
    def __init__(
        self, xmin: float = 0, ymin: float = 0, xmax: float = 1, ymax: float = 1
    ) -> None: ...
    def set_polar_box(
        self, rmin: float = 0, rmax: float = 1, tmin: float = 0, tmax: float = ...
    ) -> None: ...
    @property
    def xmin(self) -> float: ...
    @xmin.setter
    def xmin(self, value: float) -> None: ...
    @property
    def ymin(self) -> float: ...
    @ymin.setter
    def ymin(self, value: float) -> None: ...
    @property
    def xmax(self) -> float: ...
    @xmax.setter
    def xmax(self, value: float) -> None: ...
    @property
    def ymax(self) -> float: ...
    @ymax.setter
    def ymax(self, value: float) -> None: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def swap(self) -> None: ...
    def fix(self, with_margin: bool = True) -> None: ...

class View:
    width: float
    height: float
    box: Box
    def __init__(self, width: float, height: float, box: Box) -> None: ...
    @overload
    def x(self, x: None) -> None: ...
    @overload
    def x(self, x: float) -> float: ...
    @overload
    def y(self, y: None) -> None: ...
    @overload
    def y(self, y: float) -> float: ...
    @overload
    def __call__(self, xy: tuple[None, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, xy: tuple[float, None]) -> tuple[float, None]: ...
    @overload
    def __call__(self, xy: tuple[None, float]) -> tuple[None, float]: ...
    @overload
    def __call__(self, xy: tuple[float, float]) -> tuple[float, float]: ...

class ReverseView(View):
    @overload
    def y(self, y: None) -> None: ...
    @overload
    def y(self, y: float) -> float: ...

class HorizontalView(View): ...

class PolarView(View):
    @overload
    def __call__(self, rhotheta: tuple[None, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[None, object]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[object, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[float, float]) -> tuple[float, float]: ...

class PolarLogView(View):
    log10_rmax: float
    log10_rmin: float
    @overload
    def __call__(self, rhotheta: tuple[None, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[None, object]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[object, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[float, float]) -> tuple[float, float]: ...

class PolarThetaView(View):
    aperture: float
    def __init__(
        self, width: float, height: float, box: Box, aperture: float = ...
    ) -> None: ...
    @overload
    def __call__(self, rhotheta: tuple[None, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[None, object]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[object, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[float, float]) -> tuple[float, float]: ...

class PolarThetaLogView(View):
    aperture: float
    log10_tmax: float
    log10_tmin: float
    def __init__(
        self, width: float, height: float, box: Box, aperture: float = ...
    ) -> None: ...
    @overload
    def __call__(self, rhotheta: tuple[None, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[None, object]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[object, None]) -> tuple[None, None]: ...
    @overload
    def __call__(self, rhotheta: tuple[float, float]) -> tuple[float, float]: ...

_Zero: TypeAlias = Literal[0, False]

class LogView(View):
    log10_ymax: float
    log10_ymin: float
    @overload
    def y(self, y: _Zero | None) -> Literal[0]: ...
    @overload
    def y(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, y: float
    ) -> float: ...

class XLogView(View):
    log10_ymax: float
    log10_ymin: float
    @overload
    def x(self, x: _Zero | None) -> None: ...
    @overload
    def x(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, x: float
    ) -> float | None: ...

class XYLogView(XLogView, LogView):
    @overload
    def x(self, x: _Zero | None) -> None: ...
    @overload
    def x(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, x: float
    ) -> float | None: ...
    @overload
    def y(self, y: _Zero | None) -> Literal[0]: ...
    @overload
    def y(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, y: float
    ) -> float: ...

class HorizontalLogView(XLogView):
    @overload
    def x(self, x: None) -> None: ...
    @overload
    def x(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, x: float
    ) -> float | None: ...
    @overload
    def y(self, y: None) -> None: ...
    @overload
    def y(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, y: float
    ) -> float | None: ...
