from _typeshed import Incomplete

class Margin:
    top: Incomplete
    right: Incomplete
    bottom: Incomplete
    left: Incomplete
    def __init__(self, top, right, bottom, left) -> None: ...
    @property
    def x(self): ...
    @property
    def y(self): ...

class Box:
    margin: float
    def __init__(
        self, xmin: int = 0, ymin: int = 0, xmax: int = 1, ymax: int = 1
    ) -> None: ...
    def set_polar_box(
        self, rmin: int = 0, rmax: int = 1, tmin: int = 0, tmax=...
    ) -> None: ...
    @property
    def xmin(self): ...
    @xmin.setter
    def xmin(self, value) -> None: ...
    @property
    def ymin(self): ...
    @ymin.setter
    def ymin(self, value) -> None: ...
    @property
    def xmax(self): ...
    @xmax.setter
    def xmax(self, value) -> None: ...
    @property
    def ymax(self): ...
    @ymax.setter
    def ymax(self, value) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    def swap(self) -> None: ...
    def fix(self, with_margin: bool = True) -> None: ...

class View:
    width: Incomplete
    height: Incomplete
    box: Incomplete
    def __init__(self, width, height, box) -> None: ...
    def x(self, x): ...
    def y(self, y): ...
    def __call__(self, xy): ...

class ReverseView(View):
    def y(self, y): ...

class HorizontalView(View):
    width: Incomplete
    height: Incomplete
    box: Incomplete
    def __init__(self, width, height, box) -> None: ...
    def x(self, x): ...
    def y(self, y): ...

class PolarView(View):
    def __call__(self, rhotheta): ...

class PolarLogView(View):
    log10_rmax: Incomplete
    log10_rmin: Incomplete
    def __init__(self, width, height, box) -> None: ...
    def __call__(self, rhotheta): ...

class PolarThetaView(View):
    aperture: Incomplete
    def __init__(self, width, height, box, aperture=...) -> None: ...
    def __call__(self, rhotheta): ...

class PolarThetaLogView(View):
    aperture: Incomplete
    log10_tmax: Incomplete
    log10_tmin: Incomplete
    def __init__(self, width, height, box, aperture=...) -> None: ...
    def __call__(self, rhotheta): ...

class LogView(View):
    width: Incomplete
    height: Incomplete
    box: Incomplete
    log10_ymax: Incomplete
    log10_ymin: Incomplete
    def __init__(self, width, height, box) -> None: ...
    def y(self, y): ...

class XLogView(View):
    width: Incomplete
    height: Incomplete
    box: Incomplete
    log10_xmax: Incomplete
    log10_xmin: Incomplete
    def __init__(self, width, height, box) -> None: ...
    def x(self, x): ...

class XYLogView(XLogView, LogView):
    width: Incomplete
    height: Incomplete
    box: Incomplete
    log10_ymax: Incomplete
    log10_ymin: Incomplete
    log10_xmax: Incomplete
    log10_xmin: Incomplete
    def __init__(self, width, height, box) -> None: ...

class HorizontalLogView(XLogView):
    width: Incomplete
    height: Incomplete
    box: Incomplete
    log10_xmax: Incomplete
    log10_xmin: Incomplete
    def __init__(self, width, height, box) -> None: ...
    def x(self, x): ...
    def y(self, y): ...
